theme: jekyll-theme-hacker
title: <span style="color:#87CEEB">Zodiac Graphs and Interactions</span>
logo: HeaderImage.png
description: Lucía Montesinos García, Irina Ioana Avadanei, Simone Elisabeth Engelbrecht


