title: <span style="color:#8A7E4A">The Cosmic Side of Twitter</span>
logo: HeaderImage.jpg
description: Lucía Montesinos García, Irina Ioana Avadanei, Simone Elisabeth Engelbrecht
show_downloads: true
navbar-links:
 Resouces: 
  -Explainer notebook: 
theme: jekyll-theme-midnight


